name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: Deploy on new tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install SVN
      run: |
        apt-get update
        apt-get install -y subversion
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: directorist